import { ArrowLeft, Check, FileText, LayoutTemplate, Sparkles } from "lucide-react";
import Link from "next/link";
import React from "react";

const templates = [
  { id: "classic", name: "Executive Classic", category: "Reliable and structured", color: "#1d4ed8", description: "A traditional single-column layout that keeps skills, experience, and education easy for ATS systems to scan.", initials: "EC", features: ["Single-column ATS layout", "Clear section hierarchy", "Best for all industries"] },
  { id: "modern", name: "Modern Signal", category: "Focused and confident", color: "#0f766e", description: "A crisp teal-accented design for students who want a little personality while keeping every detail machine-readable.", initials: "MS", features: ["Strong visual header", "Skills-forward structure", "Great for technology roles"] },
  { id: "minimal", name: "Quiet Minimal", category: "Clean and editorial", color: "#be123c", description: "A refined, distraction-free resume that gives your achievements room to speak for themselves.", initials: "QM", features: ["Low-ink professional style", "Compact spacing", "Ideal for early careers"] },
];

const TemplatePreview = ({ template }: { template: typeof templates[number] }) => <div className="h-72 overflow-hidden rounded-lg border border-slate-200 bg-white p-5 shadow-sm" style={{ borderTop: `7px solid ${template.color}` }}><div className="flex items-start justify-between"><div><div className="text-lg font-bold text-slate-900">Aarav Sharma</div><div className="mt-1 text-[9px] text-slate-400">aarav@example.com | +91 98765 43210</div></div><div className="flex h-10 w-10 items-center justify-center rounded-full text-xs font-bold text-white" style={{ backgroundColor: template.color }}>{template.initials}</div></div><div className="my-4 h-px bg-slate-200" />{["PROFILE", "EXPERIENCE", "EDUCATION", "SKILLS"].map((section) => <div key={section} className="mb-3"><div className="mb-1 text-[9px] font-bold tracking-[0.18em]" style={{ color: template.color }}>{section}</div><div className="space-y-1"><div className="h-1.5 w-full rounded bg-slate-100" /><div className="h-1.5 w-4/5 rounded bg-slate-100" /></div></div>)}</div>;

const ResumeTemplates = () => <main className="min-h-screen bg-[#f3f6f8] pb-16 text-slate-900"><div className="mx-auto max-w-6xl px-5 pt-8 sm:px-8"><Link href="/profile" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-blue-700"><ArrowLeft size={16} /> Back to profile</Link><header className="mt-10 max-w-3xl"><p className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-blue-700"><Sparkles size={15} /> Premium resume studio</p><h1 className="text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">Choose a format that makes your work easy to find.</h1><p className="mt-4 text-base leading-7 text-slate-600">Start with an ATS-friendly foundation, then personalize the color, font, and content in the builder. Every template is designed for clarity before decoration.</p></header><div className="mt-12 grid gap-6 lg:grid-cols-3">{templates.map((template) => <article key={template.id} className="group flex flex-col rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition-shadow hover:shadow-xl"><TemplatePreview template={template} /><div className="flex flex-1 flex-col p-2 pt-5"><p className="text-xs font-bold uppercase tracking-[0.14em]" style={{ color: template.color }}>{template.category}</p><h2 className="mt-2 text-xl font-bold text-slate-950">{template.name}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{template.description}</p><ul className="mt-5 space-y-2 text-sm text-slate-700">{template.features.map((feature) => <li key={feature} className="flex items-center gap-2"><Check size={15} style={{ color: template.color }} /> {feature}</li>)}</ul><Link href={`/profile?template=${template.id}`} className="mt-6 inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold text-white transition-opacity hover:opacity-90" style={{ backgroundColor: template.color }}><FileText size={16} /> Use this template</Link></div></article>)}</div><div className="mt-10 flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-600"><LayoutTemplate className="shrink-0 text-blue-600" size={20} /><span>You can change templates, colors, and fonts at any time before generating a paid resume.</span></div></div></main>;

export default ResumeTemplates;